import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    backgroundColor: "#F2F2F2",
  },
  noImage: {
    height: 250,
    width: "100%",
    backgroundColor: "#cacaca",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#cacaca",
  },
  icon: {
    opacity: 0.3,
  },
  editButton: {
    position: "absolute",
    right: 10,
    top: 10,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollView: {
    paddingBottom: 20,
  },
  titulo: {
    fontSize: 22,
    color: '#2b88d9',
    marginLeft: 15,
    marginTop: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  data: {
    fontSize: 16,
    lineHeight: 30,
    color: '#2b88d9',
    marginLeft: 15,
    marginTop: 5
  },
  headerContainer: {
    backgroundColor: "#f5f5f5",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: 5,
    padding: 10,
    borderBottomColor: "#cacaca",
    borderBottomWidth: 1,
  },
  dateWrapper: {
    flexDirection: "row",
    alignItems: "center",
    marginEnd: 15,
  },
  descricao: {
    fontSize: 16,
    lineHeight: 30,
    color: '#222222',
    marginHorizontal: 15,
    paddingBottom: 10,
  },
  botaoMais: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    borderRadius: 50,
    backgroundColor: '#2c88d9',
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 2,
  },
  wrapper: {
    flex: 1,
    top: '10%',
    marginBottom: 40,
    alignItems: 'center',
  },
  text: {
    fontSize: 18,
    color: '#2b88d9',
    margin: 15,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  img: {
    margin: 15,
    marginRight: 0,
    width: 70,
    height: 70,
  },
  linha: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  wrapperExcluir: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  botaoExcluir: {
    height: 50,
    width: '80%',
    marginStart: '10%',
    marginBottom: 20,
    backgroundColor: '#e75757',
    borderWidth: 2,
    borderColor: '#eb4545',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  textoExcluir: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#F2F2F2',
    paddingTop: -100,
  },
  chartContainer: {
    alignItems: 'center',
    marginVertical: 20,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 10,
    elevation: 2, // Sombra para Android
    shadowColor: '#000', // Sombra para iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  resetFilterButton: {
    marginTop: 15,
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ccc',
    marginBottom: 10,
  },
  resetFilterButtonText: {
    color: '#333',
    fontSize: 14,
    fontWeight: 'bold',
  },
  pickerContainer: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    overflow: 'hidden', // Para garantir que o Picker respeite o borderRadius
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  totalExpensesText: { // NOVO: Estilo para o texto do total de despesas
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
    marginTop: 5,
  }, 
  totalDespesasPorTipo: { // NOVO: Estilo para o texto do total de despesas por tipo
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2888d9',
    marginBottom: 10,
    marginTop: 5,
  },
  listHeaderWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
});

export { styles };